name: qrcode
description: "A new Flutter project."

publish_to: "none" 


version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.6
  firebase_analytics: ^10.8.10
  firebase_auth: ^4.17.9
  firebase_storage: ^11.6.10
  flutter_pdfview: ^1.3.2
  url_launcher: ^6.2.5
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.9
  pdf: ^3.10.8
  permission_handler: ^11.3.0
  open_file: ^3.3.2
  photo_view: ^0.14.0
  dio: ^5.4.1
  flutter_spinkit: ^5.2.0
  image_pickers: ^2.0.4+9
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  scan: ^1.6.0
  mailer: ^6.1.0
  barcode_scan2: ^4.3.0
  camera: ^0.10.5+9
  get: ^4.6.6
  get_storage: ^2.1.1
  package_info_plus: ^6.0.0
  image_picker: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0


flutter:
 
  
  uses-material-design: true
  assets:
    - images/logo.png

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-BoldItalic.ttf
